### ISSUE TITLE
Send dynamic JSON

### ISSUE THREAD

**Issue by chainhead** [spring-guides/gs-rest-service#100]
I have a few questions - based on this [tutorial](https://spring.io/guides/gs/rest-service/) - as a newbie to Spring Boot. 

1. You are saying that, the representation class `Greeting.java` needs to have a get and set methods that exactly match the expected keys? 
2. How do we handle scenarios when the structure of JSON is not known well in advance? 
3. What if, in certain scenarios, some keys are left out in response because they were optional? 
4. How do we handle scenarios where keys may have spaces (e.g. https://stackoverflow.com/q/10311361/919480)? 
5. And, if values are themselves nested JSON, what should the get method return so that Jackson can marshal it properly? 

I know some of the cases mentioned above are 'edge' cases, but, the guide author must at least address these cases. Especially, coming from a MEAN stack background, all this is awful lot of work to send a JSON document!

**Comment by dsyer** [comment]
All your questions are about JSON serialization and deserialization, not specifically about Spring Boot. This guide is also intentionally narrow in scope and doesn’t need to get into the specifics of how to customize the JSON handling. FYI the sample is using [Jackson](https://github.com/FasterXML/jackson-databind), so check out their docs as well as the Spring Boot user guide sections specifically about Jackson (e.g. https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto-customize-the-jackson-objectmapper).
