### ISSUE TITLE
Example code includes broken on production GS site!

### ISSUE THREAD

**Issue by excalq** [spring-guides/gs-rest-service#101]
On https://spring.io/guides/gs/rest-service/ as well as https://spring.io/guides/gs/securing-web/, areas with an included `.java` or `.html` source section are instead showing:

```
Unresolved directive in <stdin> - include::initial/src/ ...
```

Thank you. I'm hoping to use the Spring getting started guides to dust off rusty skills before upcoming job interviews, so having this fixed would be advantageous.

**Comment by dsyer** [comment]
Working now. Probably just a cold cache.
