### ISSUE TITLE
Rest Service guide is missing source code for RestServiceApplication.java

### ISSUE THREAD

**Issue by cybersteel8** [spring-guides/gs-rest-service#103]
https://spring.io/guides/gs/rest-service/

This page contains the source code to build this application from scratch, however at the section where `@SpringBootApplication` is mentioned, there is no associated source code. I had to come here to find it.

**Comment by boraoren** [comment]
do you want to see code below in documentation?

```
package com.example.restservice;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class RestServiceApplication {

    public static void main(String[] args) {
        SpringApplication.run(RestServiceApplication.class, args);
    }

}


```

**Comment by tas09009** [comment]
I was also confused about the `@SpringBootApplication` part of the guide as well what to do with the `DemoApplication.java` that came included with the Spring Initializr download. I think adding the following steps to the official guide on the site would be helpful for beginners:

1. Create a new file called `src/main/java/com/example/restservice/RestServiceApplication.java`
2. Add code mentioned by @boraoren above. 
3. Delete `src/main/java/com/example/demo/DemoApplication.java`

**Comment by bosatsu** [comment]
I feel like just making this section more explicit would be helpful:

```
You can get a Maven build file with the necessary dependencies directly from the Spring Initializr. The following listing shows the pom.xml file that is created when you choose Maven:
```

It wasn't clear (to me anyways) that this specific `Spring Initializr` link will actually fill in all the parameters expected in this tutorial.  It also seems like the intention for this tutorial is to take that maven or graddle file and import into our IDE of choice.  Maybe that's obvious to an experienced Java developer, but wasn't obvious to me, a Python/JS developer just starting to work with Java.  

Making this more explicit would then mean that the guide would just need a sentence later on saying, something like.

```
There should also be a file called src/main/java/com/example/restservice/RestServiceApplication.java.  Open this file and let's break this down.
```

**Comment by TimFurdui** [comment]
Yea this can easily be confusing for people that are just getting into Spring.

**Comment by MoskovchenkoD** [comment]
Yeah, if you generate your project using Spring Initializr, then all 3 classes (DemoApplication, Greeting and GreetingController) should be in the same package (either com/example/demo or com/example/restservice, like the tutorial says) or else localhost:8080/greeting returns a error page.

**Comment by Buzzardo** [comment]
PR https://github.com/spring-guides/gs-rest-service/pull/125 fixes it, but I have requested a change to it.

In the meantime, you can find that class in /complete/src/main/java/com/example/consumingrest/ConsumingRestApplication.java
