### ISSUE TITLE
Not able to generate JSON Response

### ISSUE THREAD

**Issue by swaminandan** [spring-guides/gs-rest-service#38]
While trying to run this application as a Spring Boot App I get the following error
"This application has no explicit mapping for /error, so you are seeing this as a fallback."

**Comment by gregturn** [comment]
Did you visit localhost:8080/greeting?

**Comment by swaminandan** [comment]
I got the problem. I was using different packages for SpringApplication and Controller and so it was not scanning. Got it resolved by putting the application class at the top level package
