### ISSUE TITLE
Can't resolve referenced class org.springframework.cloud.netflix.eureka.server.EnableEurekaServer

### ISSUE THREAD

**Issue by donhuvy** [spring-guides/gs-rest-service#45]
1. I download zip source file: https://github.com/spring-guides/gs-rest-service/archive/master.zip

2. Then I unzip

3. Use Eclipse for JavaEE (Neon, have Spring Tool suite plugin), import Maven project in **_complete_** directory.

4. I see that Eclipse can't resolve dependency:

<img width="1440" alt="screen shot 2016-08-03 at 06 41 12" src="https://cloud.githubusercontent.com/assets/1328316/17349178/f878c376-5945-11e6-8020-677c6a8bd7f4.png">

Eclipse (or Maven) can't find referenced class **_org.springframework.cloud.netflix.eureka.server.EnableEurekaServer_**

Please help me!

**Comment by gregturn** [comment]
This appears to be opened against the wrong guide.

**Comment by donhuvy** [comment]
I am sorry. Seems, I have a mistake. This issue is not belong to this project. One month passed, then I don't remember about these projects clearly.
