### ISSUE TITLE
HTTP Status 404 - /greeting

### ISSUE THREAD

**Issue by lurodrig** [spring-guides/gs-rest-service#49]
I have just freshly cloned this repository and run the application (`mvn spring-boot:run`). I can see the nice ASCII art of spring telling me that the application is running on the root context, hooray!

However GET http://localhost:8080/greeting responses me 404, sigh...

Any idea?

**Comment by dsyer** [comment]
You ran the "complete" sample right?

**Comment by lurodrig** [comment]
Hello dsyer,

Thank you for your prompt answer!

Yes I did.

Cheers,

Luis

**Comment by dsyer** [comment]
Then I guess you need to provide more information, logs etc. It works for me.

**Comment by lurodrig** [comment]
OK, so running `mvn spring-boot:run --debug`

We can see something like:

```
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T17:41:47+01:00)
Maven home: /home/lurodrig/development/ci/apache-maven-3.3.9
Java version: 1.8.0_101, vendor: Oracle Corporation
Java home: /home/lurodrig/development/jdks/jdk1.8.0_101/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.4.0-45-generic", arch: "amd64", family: "unix"
```
.../...
```
[INFO] ------------------------------------------------------------------------
[INFO] Building gs-rest-service 0.1.0
[INFO] ------------------------------------------------------------------------
```
.../...
`[INFO] >>> spring-boot-maven-plugin:1.4.1.RELEASE:run (default-cli) > test-compile @ gs-rest-service >>>`
.../...
> [DEBUG] Classpath: [/home/lurodrig/git/gs-rest-service/complete/target/classes
>  /home/lurodrig/.m2/repository/org/springframework/boot/spring-boot-starter-web/1.4.1.RELEASE/spring-boot-starter-web-1.4.1.RELEASE.jar
>  /home/lurodrig/.m2/repository/org/springframework/boot/spring-boot-starter/1.4.1.RELEASE/spring-boot-starter-1.4.1.RELEASE.jar
>  /home/lurodrig/.m2/repository/org/springframework/boot/spring-boot/1.4.1.RELEASE/spring-boot-1.4.1.RELEASE.jar
>  /home/lurodrig/.m2/repository/org/springframework/boot/spring-boot-autoconfigure/1.4.1.RELEASE/spring-boot-autoconfigure-1.4.1.RELEASE.jar
>  /home/lurodrig/.m2/repository/org/springframework/boot/spring-boot-starter-logging/1.4.1.RELEASE/spring-boot-starter-logging-1.4.1.RELEASE.jar
>  /home/lurodrig/.m2/repository/ch/qos/logback/logback-classic/1.1.7/logback-classic-1.1.7.jar
>  /home/lurodrig/.m2/repository/ch/qos/logback/logback-core/1.1.7/logback-core-1.1.7.jar
>  /home/lurodrig/.m2/repository/org/slf4j/jcl-over-slf4j/1.7.21/jcl-over-slf4j-1.7.21.jar
>  /home/lurodrig/.m2/repository/org/slf4j/jul-to-slf4j/1.7.21/jul-to-slf4j-1.7.21.jar
>  /home/lurodrig/.m2/repository/org/slf4j/log4j-over-slf4j/1.7.21/log4j-over-slf4j-1.7.21.jar
>  /home/lurodrig/.m2/repository/org/springframework/boot/spring-boot-starter-tomcat/1.4.1.RELEASE/spring-boot-starter-tomcat-1.4.1.RELEASE.jar
>  /home/lurodrig/.m2/repository/org/apache/tomcat/embed/tomcat-embed-core/8.5.5/tomcat-embed-core-8.5.5.jar
>  /home/lurodrig/.m2/repository/org/apache/tomcat/embed/tomcat-embed-el/8.5.5/tomcat-embed-el-8.5.5.jar
>  /home/lurodrig/.m2/repository/org/apache/tomcat/embed/tomcat-embed-websocket/8.5.5/tomcat-embed-websocket-8.5.5.jar
>  /home/lurodrig/.m2/repository/org/hibernate/hibernate-validator/5.2.4.Final/hibernate-validator-5.2.4.Final.jar
>  /home/lurodrig/.m2/repository/javax/validation/validation-api/1.1.0.Final/validation-api-1.1.0.Final.jar
>  /home/lurodrig/.m2/repository/org/jboss/logging/jboss-logging/3.3.0.Final/jboss-logging-3.3.0.Final.jar
>  /home/lurodrig/.m2/repository/com/fasterxml/classmate/1.3.1/classmate-1.3.1.jar
>  /home/lurodrig/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.8.3/jackson-databind-2.8.3.jar
>  /home/lurodrig/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.8.3/jackson-annotations-2.8.3.jar
>  /home/lurodrig/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.8.3/jackson-core-2.8.3.jar
>  /home/lurodrig/.m2/repository/org/springframework/spring-web/4.3.3.RELEASE/spring-web-4.3.3.RELEASE.jar
>  /home/lurodrig/.m2/repository/org/springframework/spring-aop/4.3.3.RELEASE/spring-aop-4.3.3.RELEASE.jar
>  /home/lurodrig/.m2/repository/org/springframework/spring-beans/4.3.3.RELEASE/spring-beans-4.3.3.RELEASE.jar
>  /home/lurodrig/.m2/repository/org/springframework/spring-context/4.3.3.RELEASE/spring-context-4.3.3.RELEASE.jar
>  /home/lurodrig/.m2/repository/org/springframework/spring-webmvc/4.3.3.RELEASE/spring-webmvc-4.3.3.RELEASE.jar
>  /home/lurodrig/.m2/repository/org/springframework/spring-expression/4.3.3.RELEASE/spring-expression-4.3.3.RELEASE.jar
>  /home/lurodrig/.m2/repository/org/springframework/spring-core/4.3.3.RELEASE/spring-core-4.3.3.RELEASE.jar
>  /home/lurodrig/.m2/repository/org/slf4j/slf4j-api/1.7.21/slf4j-api-1.7.21.jar]

...And finally:

.   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v1.4.1.RELEASE)

2016-10-26 17:30:28.805  INFO 29777 --- [           main] hello.Application                        : Starting Application on lurodrig-laptop with PID 29777 (/home/lurodrig/git/gs-rest-service/complete/target/classes started by lurodrig in /home/lurodrig/git/gs-rest-service/complete)
2016-10-26 17:30:28.807  INFO 29777 --- [           main] hello.Application                        : No active profile set, falling back to default profiles: default
2016-10-26 17:30:28.843  INFO 29777 --- [           main] ationConfigEmbeddedWebApplicationContext : Refreshing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@2ab29502: startup date [Wed Oct 26 17:30:28 CEST 2016]; root of context hierarchy
2016-10-26 17:30:29.665  INFO 29777 --- [           main] s.b.c.e.t.TomcatEmbeddedServletContainer : Tomcat initialized with port(s): 8080 (http)
2016-10-26 17:30:29.674  INFO 29777 --- [           main] o.apache.catalina.core.StandardService   : Starting service Tomcat
2016-10-26 17:30:29.675  INFO 29777 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet Engine: Apache Tomcat/8.5.5
2016-10-26 17:30:29.741  INFO 29777 --- [ost-startStop-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2016-10-26 17:30:29.741  INFO 29777 --- [ost-startStop-1] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 902 ms
2016-10-26 17:30:29.780  INFO 29777 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'characterEncodingFilter' to: [/*]
2016-10-26 17:30:29.955  INFO 29777 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Registering beans for JMX exposure on startup
2016-10-26 17:30:29.986  INFO 29777 --- [           main] s.b.c.e.t.TomcatEmbeddedServletContainer : Tomcat started on port(s): 8080 (http)
2016-10-26 17:30:29.989  INFO 29777 --- [           main] hello.Application                        : Started Application in 1.548 seconds (JVM running for 3.496)

And when I make a GET request:

>  $ curl --verbose http://localhost:8080/greeting
> *   Trying 127.0.0.1...
> * Connected to localhost (127.0.0.1) port 8080 (#0)
> > GET /greeting HTTP/1.1
> > Host: localhost:8080
> > User-Agent: curl/7.47.0
> > Accept: */*
> > 
> < HTTP/1.1 404 
> < Content-Type: text/html;charset=utf-8
> < Content-Language: en
> < Content-Length: 1008
> < Date: Wed, 26 Oct 2016 15:39:01 GMT

Thank you in advance,

Luis

**Comment by dsyer** [comment]
Looks like there is no auto-configuration kicking in there. So I doubt that you are actually running the same code as me. Can you double check that you have the same code in `src/main/java` as this repo?

**Comment by lurodrig** [comment]
![image](https://cloud.githubusercontent.com/assets/2485513/19734185/e4c693aa-9ba6-11e6-960b-f37d505f27be.png)

mmm, it looks pretty much the same to me (see a debug screen-shot)

**Comment by dsyer** [comment]
OK, there must be an issue with your classpath then. You might need to drop some stuff from your local maven cache (like all of spring boot, maybe)?

**Comment by lurodrig** [comment]
OK, I do believe that you are right. I have cloned the app in another box, installing a fresh maven 3 and it works!

> {"id":1,"content":"Hello, World!"}

I've deleted all the spring packages from my local repository in my previous box. It works as well.

Thank you so much, dsyer +1!!!

**Comment by bhangalekunal** [comment]
i have get 404 while deploying spring boot war file web.war and call rest api

here is my main class code 


import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.autoconfigure.domain.EntityScan;
import org.springframework.boot.builder.SpringApplicationBuilder;
import org.springframework.boot.web.servlet.support.SpringBootServletInitializer;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.data.jpa.repository.config.EnableJpaRepositories;

@SpringBootApplication
@ComponentScan(basePackages = {"com.codemaster.*"})
@EntityScan(basePackages = {"com.codemaster.*"})
@EnableJpaRepositories(basePackages = {"com.codemaster.*"})
public class SpringApp extends SpringBootServletInitializer {
    public static void main(String[] args) {
        SpringApplication.run(SpringApp.class, args);
    }

    @Override
    protected SpringApplicationBuilder configure(SpringApplicationBuilder builder) {
        return builder.sources(SpringApp.class);
    }
}

**Comment by dsyer** [comment]
@bhangalekunal asking questions or raising issues about code that isn't in this guide is probably best done elsewhere (maybe StackOverflow?).
