### ISSUE TITLE
a new CI build should be started to reflect the document change in spring guide website.

### ISSUE THREAD

**Issue by lizhe2004** [spring-guides/gs-rest-service#50]
there is one minor change for the  referenced document of our readme.adoc file,

https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/spring-boot-application.adoc

the change is about remove the controller name "HelloController",because some projects have controller with a different name.

so I think our gs-rest-service project should kick a new CI build to reflect the change on the webpage of spring guide https://spring.io/guides/gs/rest-service/ 

I think the other guide projects  also need new CI build.  Maybe you can tell me how can I start the CI process by myself ?

**Comment by gregturn** [comment]
Resolved. I have a script to reset all guide caches, so I ran it.
