### ISSUE TITLE
Please extend this and show how POST, PUT, and PATCH methods can be implemented for XML and JSON media types

### ISSUE THREAD

**Issue by behrangsa** [spring-guides/gs-rest-service#54]
See [this issue](https://github.com/spring-projects/spring-boot/issues/7754) for more details.

It is not obvious how one should:

* Fetch the entity with a given ID from the reposiory
 * Update its properties from the JSON/XML payload (`PATCH`)
 * Replace the entity (`PUT`)
* Save it back to the repository

**Comment by Buzzardo** [comment]
I concur that that would be good content. However, we try to make the guides be completable in 15 minutes. Adding those bits would take us over the 15-minute limit. You could write a blog post and share it with the Spring community.
