### ISSUE TITLE
Page not find

### ISSUE THREAD

**Issue by jsroyal** [spring-guides/gs-rest-service#57]
Given the link in the line of  readme <br>
"This guide walks you through the process of creating a "hello world" [RESTful web service](https://github.com/spring-guides/gs-rest-service/blob/master/understanding/REST) with Spring."

![image](https://cloud.githubusercontent.com/assets/10773353/22856168/600cf68e-f0b2-11e6-9890-e1ac53900eb9.png)

This is page not found.

![image](https://cloud.githubusercontent.com/assets/10773353/22856166/55e64bd8-f0b2-11e6-83d5-25b477ef380d.png)

**Comment by gregturn** [comment]
Given the target of these guides is here => https://spring.io/guides/gs/rest-service/

...the link to Understanding REST works fine there => https://spring.io/understanding/REST.

There are many other links that have the same issue, and we can't purport to have navigation work in both platforms.

**Comment by jsroyal** [comment]
@greturn Yeah! That's Okay. But can I do this task and can I send PR for this task? It will be great sometimes both direction.

**Comment by gregturn** [comment]
What task do you wish to accomplish? 

You expressed that the link to Understanding REST doesn't work, yet I proved that it does. Just not when navigating via Github.
