### ISSUE TITLE
readme does not display all markup properly

### ISSUE THREAD

**Issue by evereveron** [spring-guides/gs-rest-service#58]
I noticed that some parts of the text in the readme were displaying as a link to the raw file rather than displaying properly. For instance, under "what you'll need". It is, however, displaying properly on the spring.io version of the tutorial. I'm guessing it's not supposed to look like that?

<img width="954" alt="screen shot 2017-04-19 at 2 13 54 pm" src="https://cloud.githubusercontent.com/assets/4021906/25195061/77662cf6-250a-11e7-82cb-ab8d06e07422.png">

**Comment by gregturn** [comment]
That's because this content is designed to be view at http://spring.io/guides. Github blocks such renderings for security reasons on their site.
