### ISSUE TITLE
getting Could not resolve org.springframework.boot:spring-boot-gradle-plugin:1.5.4.RELEASE.

### ISSUE THREAD

**Issue by HouJaI** [spring-guides/gs-rest-service#62]
i am total noob trying to get spring boot build via gradle, but i am getting the following error:

_A problem occurred configuring root project 'gradlePoC'.
> Could not resolve all files for configuration ':classpath'.
   > Could not resolve org.springframework.boot:spring-boot-gradle-plugin:1.5.4.RELEASE.
     Required by:
         project :
      > Could not resolve org.springframework.boot:spring-boot-gradle-plugin:1.5.4.RELEASE.
         > Could not get resource 'https://repo1.maven.org/maven2/org/springframework/boot/spring-boot-gradle-plugin/1.5.4.RELEASE/spring-boot-gradle-plugin-1.5.4.RELEASE.pom'.
            > Could not GET 'https://repo1.maven.org/maven2/org/springframework/boot/spring-boot-gradle-plugin/1.5.4.RELEASE/spring-boot-gradle-plugin-1.5.4.RELEASE.pom'.
               > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target_

I have downloaded the spring boot libraries and put inside my CLASSPATH in windows environment variable. please let me know how to make spring boot visible for the gradle build. Thank you.

**Comment by dsyer** [comment]
This looks like an JVM HTTP client problem. Nothing really to do with Spring or the guide, or even Gradle. Try it again in a different environment?

**Comment by dsyer** [comment]
Works for me. Closing because it is stale.
