### ISSUE TITLE
Can't import org.springframework.web.*

### ISSUE THREAD

**Issue by sd1700092** [spring-guides/gs-rest-service#63]
My pom is exactly the same as you provided,
but I can't use the annotation of RestController and RequestMapping ...
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;
the above three imports did not work at all.

**Comment by amritanshujohri** [comment]
👍  running into the same problem

**Comment by aqeelsmith** [comment]
same issue here as well. Please check.

**Comment by gregturn** [comment]
We're on 1.5.9 now, so I'm closing this issue.
