### ISSUE TITLE
add mvnw content for building from scratch

### ISSUE THREAD

**Issue by mahuntington** [spring-guides/gs-rest-service#69]
Hello!

When building this tutorial from scratch with Maven, you don't mention anything about the maven-wrapper plugin.  I'd suggest somewhere towards the end of your "Build with Maven" section telling them to run `mvn -N io.takari:maven:wrapper` or whatever you think works best.  If you follow the tutorial exactly, you get stuck at the part where you mention running `./mvnw spring-boot:run` because none of the mvnw code has been added.  It's there if you download the code to "skip the basics" but the start from scratch content you have doesn't mention anything about it.

Thanks!

**Comment by dsyer** [comment]
From the guide text:

> If you use Maven, you can run the application by using ./mvnw spring-boot:run. Alternatively, you can build the JAR file with ./mvnw clean package and then run the JAR file, as follows...

I think that covers it doesn't it?

**Comment by dsyer** [comment]
Ah! I get it. The guide doesn't explicitly describe how to add the wrapper. But it doesn't need to (since #99) because the starting point is a project generated from start.spring.io that already has the wrapper.
