### ISSUE TITLE
Java 9 is not compatible with Gradle 2.13

### ISSUE THREAD

**Issue by oleg-sidorov** [spring-guides/gs-rest-service#71]
I tried to build the project in "complete" folder using IntelliJ IDEA + JDK 9 + Gradle and encountered the error:

_"Could not determine java version from '9.0.4 '"_

Then I upgraded Gradle to version 4.4.1 in gradle-wrapper.properties:

_distributionUrl=https\://services.gradle.org/distributions/gradle-**4.4.1**-bin.zip_

and it helped.

Please update Gradle in the source code.

**Comment by gregturn** [comment]
@jbsf Since we've updated the guide to Gradle 4.6, perhaps you would like to check again.
