### ISSUE TITLE
Session "Build with Maven" doesn't expand when clicked on Firefox

### ISSUE THREAD

**Issue by aldonogueira** [spring-guides/gs-rest-service#84]
The sessions "Build with Maven" and "Build with your IDE" don't expand when clicked on Firefox. Luckily I wanted Gradle :smile: The hand cursor appears, but nothing happens when the user clicks on them. I have tested on Chrome and it works fine.  

This is possibly not the right place to create this issue but I couldn't find where exactly this bug belongs. Please tell me if there is a more appropriate project to do this.

**Comment by dsyer** [comment]
This is the correct place, but I don't think those sections exist any more (as of #99). If you see the same issue with any other guides please open an issue (one is enough - they all share the same scripts).
