### ISSUE TITLE
HTTP 404 Status with spring boot 1.5.17.RELEASE

### ISSUE THREAD

**Issue by oberlatz** [spring-guides/gs-rest-service#87]
The service in gs-rest-service/complete responds with a 404 status code when calling http://localhost:8080/greeting. This happens with spring boot 1.5.17.

The service responds successfully with spring boot 1.5.16, 2.0.5 and 2.1.0.

The service is started from within Spring Tool Suite 3.9.5.RELEASE on a Linux openSUSE Tumbleweed version 20181107.

**Comment by dsyer** [comment]
Spring Boot 1.5 is EOL and this guide is now on 2.x.
